run:
  modules-download-mode: readonly
  timeout: 10m

linters:
  disable-all: true
  fast: true
  enable:
    - bodyclose
    - dupword
    - errcheck
    - errname
    - errorlint
    - exportloopref
    - gochecknoinits
    - godot
    - gofmt
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - loggercheck
    - nestif
    - nilerr
    - noctx
    - paralleltest
    - prealloc
    - predeclared
    - reassign
    - revive
    - tenv
    - testableexamples
    - thelper
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: cirello.io/dynamolock/v4
  revive:
    rules:
      - name: atomic
      - name: blank-imports
      - name: comment-spacings
      - name: context-as-argument
      - name: context-keys-type
      - name: datarace
      - name: deep-exit
      - name: defer
      - name: dot-imports
      - name: duplicated-imports
      - name: early-return
      - name: empty-block
      - name: empty-lines
      - name: error-naming
      - name: error-return
      - name: error-strings
      - name: errorf
      - name: exported
      - name: get-return
      - name: import-shadowing
      - name: indent-error-flow
      - name: optimize-operands-order
      - name: package-comments
      - name: range
      - name: range-val-address
      - name: receiver-naming
      - name: redundant-import-alias
      - name: string-of-int
      - name: struct-tag
      - name: superfluous-else
      - name: time-equal
      - name: time-naming
      - name: unexported-naming
      - name: unexported-return
      - name: unreachable-code
      - name: use-any
      - name: useless-break
      - name: var-declaration
      - name: var-naming
      - name: waitgroup-by-value
      - name: unhandled-error
        arguments: ["fmt\\.Print.*"]


