name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "stable"

      - name: Download DynamoDB Local
        working-directory: v2/
        run: |
          set -e
          make local-dynamodb

      - name: Test
        working-directory: v2/
        run: |
          go test -v
