name: Go

on:
  push:
    branches: [master]
    paths:
      - 'v2/**'
  pull_request:
    branches: [master]
    paths:
      - 'v2/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "stable"

      - name: Download DynamoDB Local
        working-directory: v2/
        run: |
          set -e
          make local-dynamodb

      - name: Test
        working-directory: v2/
        run: |
          make test

      - name: Linters
        working-directory: v2/
        run: |
          make linters
